name: Forge Muscle APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev libgstreamer1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good libsqlite3-dev lld openjdk-17-jdk unzip zip

      - name: Install Python Tools
        run: |
          pip install --upgrade pip
          pip install --upgrade "cython<3.0.0" wheel "setuptools<70.0.0" buildozer

      - name: Build with Buildozer
        run: |
          rm -rf .buildozer
          # On lance la forge, et SI ELLE ÉCHOUE, on affiche les logs cachés
          buildozer -v android debug || (find .buildozer/android/platform/build-arm64-v8a/build/other_builds/python3 -name "config.log" -exec cat {} + && exit 1)
        
      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Muscle-Agent-APK
          path: bin/*.apk
