name: Forge Muscle APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Recuperation des fichiers
        uses: actions/checkout@v4

      - name: 2. Verification visuelle (Regarde le log de cette etape)
        run: ls -R

      - name: 3. Installation des outils
        run: |
          sudo apt update
          sudo apt install -y build-essential git python3-dev libsqlite3-dev lld
          pip install --upgrade "cython<3.0.0" buildozer setuptools

      - name: 4. Forge de l'APK
        run: |
          # On se force a etre au bon endroit
          yes | buildozer android debug
        
      - name: 5. Livraison
        uses: actions/upload-artifact@v4
        with:
          name: Muscle-Agent-APK
          path: bin/*.apk
