name: Forge Muscle APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Mis à jour v4

      - name: Set up Python
        uses: actions/setup-python@v5 # Mis à jour v5
        with:
          python-version: '3.10'

      - name: Install Buildozer dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev libgstreamer1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good libsqlite3-dev lld
          pip install --upgrade "cython<3.0.0" buildozer setuptools

      - name: Build with Buildozer
        run: |
          yes | buildozer android debug
        
      - name: Upload APK
        uses: actions/upload-artifact@v4 # LA CORRECTION EST ICI (v4)
        with:
          name: Muscle-Agent-APK
          path: bin/*.apk
